[package]
name = "rls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
predicates = "*"
ansi_term = "*"
lazy_static = "*"
is_executable = "*"
walkdir = "*"